name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build godot_pcg
      run: cargo build --verbose
      working-directory: pcg/godot_pcg
    
    - name: Run tests for godot_pcg
      run: cargo test --verbose
      working-directory: pcg/godot_pcg
    
    - name: Build graph_editor
      run: cargo build --verbose
      working-directory: pcg/graph_editor
    
    - name: Run tests for graph_editor
      run: cargo test --verbose
      working-directory: pcg/graph_editor
    
    - name: Upload godot_pcg artifacts
      uses: actions/upload-artifact@v4
      with:
        name: godot_pcg-build
        path: pcg/godot_pcg/target/
    
    - name: Upload graph_editor artifacts
      uses: actions/upload-artifact@v4
      with:
        name: graph_editor-build
        path: pcg/graph_editor/target/
